import type Rgb from "../types/Rgb.js";
import fromHex from "../utility/hexToRgb.js";

/**
 * Crayola Crayon Colors. Colors are not uniformly distributed. Insufficient variety of distinct colors for computer use.
 * @see {@link https://people.csail.mit.edu/jaffer/Color/Dictionaries#crayola | Color-Name Dictionaries}
 * @public
 */
const crayola: Map<string, Rgb> = new Map<string, Rgb>([
	["black", fromHex(0x232323)],
	["outer space", fromHex(0x414a4c)],
	["midnight blue", fromHex(0x1a4876)],
	["navy blue", fromHex(0x1974d2)],
	["denim", fromHex(0x2b6cc4)],
	["tropical rain forest", fromHex(0x17806d)],
	["pine green", fromHex(0x158078)],
	["turquoise blue", fromHex(0x77dde7)],
	["aquamarine", fromHex(0x78dbe2)],
	["white", fromHex(0xededed)],
	["piggy pink", fromHex(0xfddde6)],
	["timberwolf", fromHex(0xdbd7d2)],
	["periwinkle", fromHex(0xc5d0e6)],
	["silver", fromHex(0xcdc5c2)],
	["cornflower", fromHex(0x9aceeb)],
	["sky blue", fromHex(0x80daeb)],
	["blue bell", fromHex(0xa2a2d0)],
	["wild blue yonder", fromHex(0xa2add0)],
	["cadet blue", fromHex(0xb0b7c6)],
	["manatee", fromHex(0x979aaa)],
	["gray", fromHex(0x95918c)],
	["blue green", fromHex(0x199ebd)],
	["cerulean", fromHex(0x1dacd6)],
	["pacific blue", fromHex(0x1ca9c9)],
	["robin egg blue", fromHex(0x1fcecb)],
	["green", fromHex(0x1cac78)],
	["mountain meadow", fromHex(0x30ba8f)],
	["shamrock", fromHex(0x45cea2)],
	["caribbean green", fromHex(0x1cd3a2)],
	["fern", fromHex(0x71bc78)],
	["forest green", fromHex(0x6dae81)],
	["jungle green", fromHex(0x3bb08f)],
	["asparagus", fromHex(0x87a96b)],
	["beaver", fromHex(0x9f8170)],
	["olive green", fromHex(0xbab86c)],
	["yellow green", fromHex(0xc5e384)],
	["gold", fromHex(0xe7c697)],
	["desert sand", fromHex(0xefcdb8)],
	["peach", fromHex(0xffcfab)],
	["apricot", fromHex(0xfdd9b5)],
	["almond", fromHex(0xefdbc5)],
	["banana mania", fromHex(0xfce9bd)],
	["spring green", fromHex(0xeceabe)],
	["green yellow", fromHex(0xf0e891)],
	["canary", fromHex(0xfffdad)],
	["sea green", fromHex(0x9fe2bf)],
	["granny smith apple", fromHex(0xa8e4a0)],
	["screamin' green", fromHex(0x76ff7a)],
	["inch worm", fromHex(0xb2ec5d)],
	["electric lime", fromHex(0xceff1d)],
	["laser lemon", fromHex(0xfdfc74)],
	["unmellow yellow", fromHex(0xfdfc74)],
	["goldenrod", fromHex(0xfcd975)],
	["dandelion", fromHex(0xfddb6d)],
	["yellow", fromHex(0xfce883)],
	["sunglow", fromHex(0xffcf48)],
	["shadow", fromHex(0x8a795d)],
	["sepia", fromHex(0xa5694f)],
	["brown", fromHex(0xb4674d)],
	["chestnut", fromHex(0xbc5d58)],
	["fuzzy wuzzy brown", fromHex(0xcc6666)],
	["maroon", fromHex(0xc8385a)],
	["jazzberry jam", fromHex(0xc63061)],
	["brick red", fromHex(0xcb4154)],
	["mahogany", fromHex(0xcd4a4c)],
	["scarlet", fromHex(0xfc2847)],
	["red", fromHex(0xee204d)],
	["razzmatazz", fromHex(0xe3256b)],
	["orange", fromHex(0xff7538)],
	["neon carrot", fromHex(0xffa343)],
	["burnt orange", fromHex(0xff7f49)],
	["mango tango", fromHex(0xff8243)],
	["yellow orange", fromHex(0xffb653)],
	["melon", fromHex(0xfdbcb4)],
	["macaroni and cheese", fromHex(0xffbd88)],
	["salmon", fromHex(0xff9baa)],
	["vivid tangerine", fromHex(0xffa089)],
	["bittersweet", fromHex(0xfd7c6e)],
	["copper", fromHex(0xdd9475)],
	["atomic tangerine", fromHex(0xffa474)],
	["tan", fromHex(0xfaa76c)],
	["tumbleweed", fromHex(0xdeaa88)],
	["antique brass", fromHex(0xcd9575)],
	["raw sienna", fromHex(0xd68a59)],
	["burnt sienna", fromHex(0xea7e5d)],
	["radical red", fromHex(0xff496c)],
	["wild watermelon", fromHex(0xfc6c85)],
	["outrageous orange", fromHex(0xff6e4a)],
	["sunset orange", fromHex(0xfd5e53)],
	["red orange", fromHex(0xff5349)],
	["wild strawberry", fromHex(0xff43a4)],
	["razzle dazzle rose", fromHex(0xff48d0)],
	["magenta", fromHex(0xf664af)],
	["violet red", fromHex(0xf75394)],
	["blush", fromHex(0xde5d83)],
	["fuchsia", fromHex(0xc364c5)],
	["purple mountain's majesty", fromHex(0x9d81ba)],
	["wisteria", fromHex(0xcda4de)],
	["orchid", fromHex(0xe6a8d7)],
	["tickle me pink", fromHex(0xfc89ac)],
	["pink sherbet", fromHex(0xf78fa7)],
	["mauvelous", fromHex(0xef98aa)],
	["carnation pink", fromHex(0xffaacc)],
	["lavender", fromHex(0xfcb4d5)],
	["cotton candy", fromHex(0xffbcd9)],
	["pink flamingo", fromHex(0xfc74fd)],
	["shocking pink", fromHex(0xfb7efd)],
	["hot magenta", fromHex(0xff1dce)],
	["purple pizzazz", fromHex(0xff1dce)],
	["cerise", fromHex(0xdd4492)],
	["red violet", fromHex(0xc0448f)],
	["vivid violet", fromHex(0x8f509d)],
	["plum", fromHex(0x8e4585)],
	["eggplant", fromHex(0x6e5160)],
	["violet", fromHex(0x926eae)],
	["blue violet", fromHex(0x7366bd)],
	["indigo", fromHex(0x5d76cb)],
	["blue", fromHex(0x1f75fe)],
	["royal purple", fromHex(0x7851a9)],
	["purple heart", fromHex(0x7442c8)]
]);

export default crayola;
